language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

install:
  - composer self-update
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
